import os
import pygame
BLOCK_SIZE = 100
BEETROOTS_GROW_TIME = 5
BEETROOTS_MAXIMUM_STATE = 16
BEETROOTSTAGE1 = pygame.image.load(os.path.join('resources', 'beetroots_stage1.png'))
BEETROOTSTAGE1 = pygame.transform.scale(BEETROOTSTAGE1, (BLOCK_SIZE, BLOCK_SIZE))
BEETROOTSTAGE2 = pygame.image.load(os.path.join('resources', 'beetroots_stage2.png'))
BEETROOTSTAGE2 = pygame.transform.scale(BEETROOTSTAGE2, (BLOCK_SIZE, BLOCK_SIZE))
BEETROOTSTAGE3 = pygame.image.load(os.path.join('resources', 'beetroots_stage3.png'))
BEETROOTSTAGE3 = pygame.transform.scale(BEETROOTSTAGE3, (BLOCK_SIZE, BLOCK_SIZE))
BEETROOTSTAGE4 = pygame.image.load(os.path.join('resources', 'beetroots_stage4.png'))
BEETROOTSTAGE4 = pygame.transform.scale(BEETROOTSTAGE4, (BLOCK_SIZE, BLOCK_SIZE))
CARROTS_GROW_TIME = 5
CARROTS_MAXIMUM_STATE = 16
CARROTSTAGE1 = pygame.image.load(os.path.join('resources', 'carrots_stage1.png'))
CARROTSTAGE1 = pygame.transform.scale(CARROTSTAGE1, (BLOCK_SIZE, BLOCK_SIZE))
CARROTSTAGE2 = pygame.image.load(os.path.join('resources', 'carrots_stage2.png'))
CARROTSTAGE2 = pygame.transform.scale(CARROTSTAGE2, (BLOCK_SIZE, BLOCK_SIZE))
CARROTSTAGE3 = pygame.image.load(os.path.join('resources', 'carrots_stage3.png'))
CARROTSTAGE3 = pygame.transform.scale(CARROTSTAGE3, (BLOCK_SIZE, BLOCK_SIZE))
CARROTSTAGE4 = pygame.image.load(os.path.join('resources', 'carrots_stage4.png'))
CARROTSTAGE4 = pygame.transform.scale(CARROTSTAGE4, (BLOCK_SIZE, BLOCK_SIZE))
DIRT = pygame.image.load(os.path.join('resources', 'dirt.png'))
DIRT = pygame.transform.scale(DIRT, (BLOCK_SIZE, BLOCK_SIZE))
FARMLAND = pygame.image.load(os.path.join('resources', 'farmland.png'))
FARMLAND = pygame.transform.scale(FARMLAND, (BLOCK_SIZE, BLOCK_SIZE))
FARMLANDMOIST = pygame.image.load(os.path.join('resources', 'farmland_moist.png'))
FARMLANDMOIST = pygame.transform.scale(FARMLANDMOIST, (BLOCK_SIZE, BLOCK_SIZE))
FPS = 1
POTATOES_GROW_TIME = 5
POTATOES_MAXIMUM_STATE = 16
POTATOSTAGE1 = pygame.image.load(os.path.join('resources', 'potatoes_stage1.png'))
POTATOSTAGE1 = pygame.transform.scale(POTATOSTAGE1, (BLOCK_SIZE, BLOCK_SIZE))
POTATOSTAGE2 = pygame.image.load(os.path.join('resources', 'potatoes_stage2.png'))
POTATOSTAGE2 = pygame.transform.scale(POTATOSTAGE2, (BLOCK_SIZE, BLOCK_SIZE))
POTATOSTAGE3 = pygame.image.load(os.path.join('resources', 'potatoes_stage3.png'))
POTATOSTAGE3 = pygame.transform.scale(POTATOSTAGE3, (BLOCK_SIZE, BLOCK_SIZE))
POTATOSTAGE4 = pygame.image.load(os.path.join('resources', 'potatoes_stage4.png'))
POTATOSTAGE4 = pygame.transform.scale(POTATOSTAGE4, (BLOCK_SIZE, BLOCK_SIZE))
WIDTH, HEIGHT = 1000, 1000
WIN = pygame.display.set_mode((WIDTH, HEIGHT))
TRACTOR = pygame.image.load(os.path.join('resources', 'tractor.png'))
TRACTOR = pygame.transform.scale(TRACTOR, (BLOCK_SIZE, BLOCK_SIZE))
TRACTOR_FERTILIZER = 2
TRACTOR_FUEL = 200
TRACTOR_AMOUNT_OF_SEEDS_EACH_TYPE = 20
TRACTOR_MAXIMUM_COLLECTED_PLANTS = 80
TRACTOR_WATER_LEVEL = 40
WHEAT_GROW_TIME = 5
WHEAT_MAXIMUM_STATE = 21
WHEATSTAGE1 = pygame.image.load(os.path.join('resources', 'wheat_stage1.png'))
WHEATSTAGE1 = pygame.transform.scale(WHEATSTAGE1, (BLOCK_SIZE, BLOCK_SIZE))
WHEATSTAGE2 = pygame.image.load(os.path.join('resources', 'wheat_stage2.png'))
WHEATSTAGE2 = pygame.transform.scale(WHEATSTAGE2, (BLOCK_SIZE, BLOCK_SIZE))
WHEATSTAGE3 = pygame.image.load(os.path.join('resources', 'wheat_stage3.png'))
WHEATSTAGE3 = pygame.transform.scale(WHEATSTAGE3, (BLOCK_SIZE, BLOCK_SIZE))
WHEATSTAGE4 = pygame.image.load(os.path.join('resources', 'wheat_stage4.png'))
WHEATSTAGE4 = pygame.transform.scale(WHEATSTAGE4, (BLOCK_SIZE, BLOCK_SIZE))
WHEATSTAGE5 = pygame.image.load(os.path.join('resources', 'wheat_stage5.png'))
WHEATSTAGE5 = pygame.transform.scale(WHEATSTAGE5, (BLOCK_SIZE, BLOCK_SIZE))